### ISSUE TITLE
What is the most efficient way to create a 'likes' stream?

### ISSUE THREAD

**Issue by cvrsor** [schneems/likeable#12]
Hello,

I have added the Likeable library to my app successfully, now each user can like my 'Posts' model. I am currently examining what is the most efficient way to show a _'likes stream'_ in each user's profile page, something like:

`'User XXX liked your post 'Blablablabla' on 25 Dec 2011
User YYY liked your post 'BiriBiriBiriBiri' on 26 Dec 2011'`

I was thinking of implementing a seperate 'list' per Post in my Redis instance, adding the above sentence whenever a like happens. On the other hand, the Likeable library already has the .likes class that lists likes (including users, date etc) for each Post. 

I am thinking that using the _.likes_ class may **hinder my app's performance**, indeed everytime a user accesses his profile page, my controller would have to iterate through all his Posts, check if there are any likes for each Post, then retrieve the required information (user id, username, date, etc) and compose the above sentence for every like of every post..

Any suggestions?

Many thanks for your help!
Alex

**Comment by schneems** [comment]
Indeed the likes method is very inefficient though you could always cache it with memcache which would be the easiest thing to do. Setting it to auto expire in a few hours. If you ever intend on having other activity in a the feed I recommend the list method since you could then have more activity than just likes. We used a sorted set to store notifications in at Gowalla which worked well. Using the time as the score.

Does that help?

**Comment by cvrsor** [comment]
Hello Richard,

And thank you for your reply!
I may need to add more information into my 'stream' implementation, so I think it is best to add a separate key for each 'user stream'. I have already worked on the following:

When a user 'likes' a Post, I pass some extra parameters into the POST that will be required to compose the notification sentence:

`````` $.ajax({
type: 'POST',
data: { _method:'POST', tape_id: "<%= @tape.id %>", tapeinfo: JSON.stringify({tape_name: "<%= @tape.name %>", tape_user_id: "<%= @tape.user.id %>" ...})},```
_note the tapeinfo key_

The likes_controller gets the JSON and pushes it into a redis list, named after the related user id (i.e. "stream35" if the like notification should appear into the stream of user with id '35':
```streamjson = JSON.parse params[:tapeinfo]
streamjson["like_user"] = current_user.username
streamjson["like_user_id"] = current_user.id
streamjson["like_date"] = Time.now
$REDIS.lpush("stream"+streamjson["tape_user_id"], streamjson)```

Then when showing the user's profile, I get the 10 most recent notifications by calling:
```$REDIS.lrange("stream35",0,10)```
(note that the above call returns the saved JSON information, then I can render the formatted sentence using a helper etc)

**My current challenge** is how to remove the relevant notification if a user UNLIKES a Post, i.e. after an unlike occurs I should somehow fetch the element from the list key and delete it so that it does not continue to show into the stream. Thing is, the LREM command can remove an element from the list only if you know the full contents of the element. 

In my case, it would be convenient if I could just reference this list element by the user id that liked the Post, and then when the 'unlike' event happens just remove that element using his known user id.

What do you think on the unlike challenge? Would sorted lists handle this complexity more efficiently? How did you implement 'unlikes' in Gowalla's notifications?

Many many thanks for your help, really appreciated!
``````

**Comment by schneems** [comment]
If you want you can implement the adding to list behavior in the model rather than the controller using the `#after_like` callback. Though there is currently not an after_unlike callback (thought that would be a great feature to add). 

With unliking an object at Gowalla, we took the twitter favorite approach, the event occurred and your notice reflects that, even if the same user goes back and unlikes the same object it doesn't mean that they didn't like it in the first place (even if that was an accident). It is much much simpler that way. Also you never have a user get a notification and then have the same notification disappear. 

If you wanted you could store a json object in your sorted set so. 

If user #99 likes post #33 that user #12 made you could store that like this:

``` ruby
Redis.zadd('users:12:notifications', Time.now.to_i, {:event => 'liked', :target => 'post', :target_id => '33', :user_id => 99}.to_json)
```

And then build your notification messages out of your json hash.

Since we're not storing the time in the value of the sorted set, when a user unlikes the object if we wanted to we could easily do this

``` ruby
Redis.zrem('users:12:notifications', {:event => 'liked', :target => 'post', :target_id => '33', :user_id => 99}.to_json)
```

By storing the actual message in redis, you're using up quite a bit more space than you need to and if you ever want to change the message you will need to go back, parse and re-write all your redis values. I strongly recommend only storing the necessary info to re-build the notification as above.

**Comment by cvrsor** [comment]
I think for the time being I will follow your reasoning and not remove the notification on 'unlike'. Makes sense and keeps things simpler.
Though I can see with your example how I could implement such a feature.

Thank you for your time and help!
